### ISSUE TITLE
Remember window state

### ISSUE THREAD

**Issue by arshubham** [bartzaalberg/snaptastic#50] opened 2018-09-22 10:14 UTC

**Comment by unbelievableflavour** [comment] 2019-01-23 09:23
Do you mean you want to start on the last page you where? Because i wouldn't want to start on an app i last installed. I could however save state for list-view and welcome-view. So that when visiting list-view it saves list-view.

**Comment by arshubham** [comment] 2019-01-23 09:57
No, I mean windows size and position on the desktop. Currently it is reset in each session.

**Comment by peteruithoven** [comment] 2019-01-23 10:29
In that case https://github.com/bartzaalberg/snaptastic/issues/58 was a duplicate of this issue?

**Comment by unbelievableflavour** [comment] 2019-01-23 10:40
Yup. Closing this.

**Closed as completed by unbelievableflavour** 2019-01-23 10:40 UTC
